VER_UE4_SERIALIZE_TEXT_IN_PACKAGES            = 459
VER_UE4_ADDED_PACKAGE_SUMMARY_LOCALIZATION_ID = 516
VER_UE4_NON_OUTER_PACKAGE_IMPORT              = 520
VER_UE4_AUTOMATIC_VERSION                     = 522

VER_UE5_OPTIONAL_RESOURCES                    = 1003
VER_UE5_LARGE_WORLD_COORDINATES               = 1004
VER_UE5_AUTOMATIC_VERSION                     = 1004